// Generated by bin/gen-gettext-plurals from CLDR 48.0 (cldr-core):
// do not edit. Copyright © 1991-2025 Unicode, Inc. Unicode License v3,
// https://www.unicode.org/license.txt.
// Each language's gettext `Plural-Forms`, its forms the CLDR categories
// integers reach, in CLDR's order (#812).
export const GETTEXT_PLURALS: Record<
  string,
  { nplurals: number; plural: string; forms: string[] }
> = {
  "af": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ak": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "am": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "an": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ar": {
    nplurals: 6,
    plural: "(n==0) ? 0 : (n==1) ? 1 : (n==2) ? 2 : ((n%100>=3 && n%100<=10)) ? 3 : ((n%100>=11 && n%100<=99)) ? 4 : 5",
    forms: ["zero","one","two","few","many","other"],
  },
  "ars": {
    nplurals: 6,
    plural: "(n==0) ? 0 : (n==1) ? 1 : (n==2) ? 2 : ((n%100>=3 && n%100<=10)) ? 3 : ((n%100>=11 && n%100<=99)) ? 4 : 5",
    forms: ["zero","one","two","few","many","other"],
  },
  "as": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "asa": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ast": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "az": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "bal": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "be": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","many"],
  },
  "bem": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "bez": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "bg": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "bho": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "blo": {
    nplurals: 3,
    plural: "(n==0) ? 0 : (n==1) ? 1 : 2",
    forms: ["zero","one","other"],
  },
  "bm": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "bn": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "bo": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "br": {
    nplurals: 5,
    plural: "((n%10==1 && !(n%100==11 || n%100==71 || n%100==91))) ? 0 : ((n%10==2 && !(n%100==12 || n%100==72 || n%100==92))) ? 1 : ((((n%10>=3 && n%10<=4) || n%10==9) && !((n%100>=10 && n%100<=19) || (n%100>=70 && n%100<=79) || (n%100>=90 && n%100<=99)))) ? 2 : ((!(n==0) && n%1000000==0)) ? 3 : 4",
    forms: ["one","two","few","many","other"],
  },
  "brx": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "bs": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "ca": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "ce": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ceb": {
    nplurals: 2,
    plural: "((n==1 || n==2 || n==3) || !(n%10==4 || n%10==6 || n%10==9)) ? 0 : 1",
    forms: ["one","other"],
  },
  "cgg": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "chr": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ckb": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "cs": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((n>=2 && n<=4)) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "csw": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "cv": {
    nplurals: 3,
    plural: "(n==0) ? 0 : (n==1) ? 1 : 2",
    forms: ["zero","one","other"],
  },
  "cy": {
    nplurals: 6,
    plural: "(n==0) ? 0 : (n==1) ? 1 : (n==2) ? 2 : (n==3) ? 3 : (n==6) ? 4 : 5",
    forms: ["zero","one","two","few","many","other"],
  },
  "da": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "de": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "doi": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "dsb": {
    nplurals: 4,
    plural: "(n%100==1) ? 0 : (n%100==2) ? 1 : ((n%100>=3 && n%100<=4)) ? 2 : 3",
    forms: ["one","two","few","other"],
  },
  "dv": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "dz": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "ee": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "el": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "en": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "eo": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "es": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "et": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "eu": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "fa": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ff": {
    nplurals: 2,
    plural: "((n==0 || n==1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "fi": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "fil": {
    nplurals: 2,
    plural: "((n==1 || n==2 || n==3) || !(n%10==4 || n%10==6 || n%10==9)) ? 0 : 1",
    forms: ["one","other"],
  },
  "fo": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "fr": {
    nplurals: 3,
    plural: "((n==0 || n==1)) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "fur": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "fy": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ga": {
    nplurals: 5,
    plural: "(n==1) ? 0 : (n==2) ? 1 : ((n>=3 && n<=6)) ? 2 : ((n>=7 && n<=10)) ? 3 : 4",
    forms: ["one","two","few","many","other"],
  },
  "gd": {
    nplurals: 4,
    plural: "((n==1 || n==11)) ? 0 : ((n==2 || n==12)) ? 1 : (((n>=3 && n<=10) || (n>=13 && n<=19))) ? 2 : 3",
    forms: ["one","two","few","other"],
  },
  "gl": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "gsw": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "gu": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "guw": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "gv": {
    nplurals: 4,
    plural: "(n%10==1) ? 0 : (n%10==2) ? 1 : ((n%100==0 || n%100==20 || n%100==40 || n%100==60 || n%100==80)) ? 2 : 3",
    forms: ["one","two","few","other"],
  },
  "ha": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "haw": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "he": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "hi": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "hnj": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "hr": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "hsb": {
    nplurals: 4,
    plural: "(n%100==1) ? 0 : (n%100==2) ? 1 : ((n%100>=3 && n%100<=4)) ? 2 : 3",
    forms: ["one","two","few","other"],
  },
  "hu": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "hy": {
    nplurals: 2,
    plural: "((n==0 || n==1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "ia": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "id": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "ie": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ig": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "ii": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "io": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "is": {
    nplurals: 2,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : 1",
    forms: ["one","other"],
  },
  "it": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "iu": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "ja": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "jbo": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "jgo": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "jmc": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "jv": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "jw": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "ka": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "kab": {
    nplurals: 2,
    plural: "((n==0 || n==1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "kaj": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "kcg": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "kde": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "kea": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "kk": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "kkj": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "kl": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "km": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "kn": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ko": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "kok": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "kok-Latn": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ks": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ksb": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ksh": {
    nplurals: 3,
    plural: "(n==0) ? 0 : (n==1) ? 1 : 2",
    forms: ["zero","one","other"],
  },
  "ku": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "kw": {
    nplurals: 6,
    plural: "(n==0) ? 0 : (n==1) ? 1 : ((n%100==2 || n%100==22 || n%100==42 || n%100==62 || n%100==82) || (n%1000==0 && ((n%100000>=1000 && n%100000<=20000) || n%100000==40000 || n%100000==60000 || n%100000==80000)) || (!(n==0) && n%1000000==100000)) ? 2 : ((n%100==3 || n%100==23 || n%100==43 || n%100==63 || n%100==83)) ? 3 : ((!(n==1) && (n%100==1 || n%100==21 || n%100==41 || n%100==61 || n%100==81))) ? 4 : 5",
    forms: ["zero","one","two","few","many","other"],
  },
  "ky": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "lag": {
    nplurals: 3,
    plural: "(n==0) ? 0 : (((n==0 || n==1) && !(n==0))) ? 1 : 2",
    forms: ["zero","one","other"],
  },
  "lb": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "lg": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "lij": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "lkt": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "lld": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "ln": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "lo": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "lt": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100>=11 && n%100<=19))) ? 0 : (((n%10>=2 && n%10<=9) && !(n%100>=11 && n%100<=19))) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "lv": {
    nplurals: 3,
    plural: "(n%10==0 || (n%100>=11 && n%100<=19)) ? 0 : ((n%10==1 && !(n%100==11))) ? 1 : 2",
    forms: ["zero","one","other"],
  },
  "mas": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "mg": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "mgo": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "mk": {
    nplurals: 2,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : 1",
    forms: ["one","other"],
  },
  "ml": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "mn": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "mo": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==0 || (!(n==1) && (n%100>=1 && n%100<=19))) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "mr": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ms": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "mt": {
    nplurals: 5,
    plural: "(n==1) ? 0 : (n==2) ? 1 : (n==0 || (n%100>=3 && n%100<=10)) ? 2 : ((n%100>=11 && n%100<=19)) ? 3 : 4",
    forms: ["one","two","few","many","other"],
  },
  "my": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "nah": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "naq": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "nb": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "nd": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ne": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "nl": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "nn": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "nnh": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "no": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "nqo": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "nr": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "nso": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "ny": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "nyn": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "om": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "or": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "os": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "osa": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "pa": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "pap": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "pcm": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "pl": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","many"],
  },
  "prg": {
    nplurals: 3,
    plural: "(n%10==0 || (n%100>=11 && n%100<=19)) ? 0 : ((n%10==1 && !(n%100==11))) ? 1 : 2",
    forms: ["zero","one","other"],
  },
  "ps": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "pt": {
    nplurals: 3,
    plural: "((n>=0 && n<=1)) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "pt-PT": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "rm": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ro": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==0 || (!(n==1) && (n%100>=1 && n%100<=19))) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "rof": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ru": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","many"],
  },
  "rwk": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "sah": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "saq": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "sat": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "sc": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "scn": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "sd": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "sdh": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "se": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "seh": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ses": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "sg": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "sgs": {
    nplurals: 4,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (n==2) ? 1 : ((!(n==2) && (n%10>=2 && n%10<=9) && !(n%100>=11 && n%100<=19))) ? 2 : 3",
    forms: ["one","two","few","other"],
  },
  "sh": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "shi": {
    nplurals: 3,
    plural: "(n==0 || n==1) ? 0 : ((n>=2 && n<=10)) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "si": {
    nplurals: 2,
    plural: "((n==0 || n==1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "sk": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((n>=2 && n<=4)) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "sl": {
    nplurals: 4,
    plural: "(n%100==1) ? 0 : (n%100==2) ? 1 : ((n%100>=3 && n%100<=4)) ? 2 : 3",
    forms: ["one","two","few","other"],
  },
  "sma": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "smi": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "smj": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "smn": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "sms": {
    nplurals: 3,
    plural: "(n==1) ? 0 : (n==2) ? 1 : 2",
    forms: ["one","two","other"],
  },
  "sn": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "so": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "sq": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "sr": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","other"],
  },
  "ss": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ssy": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "st": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "su": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "sv": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "sw": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "syr": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ta": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "te": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "teo": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "th": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "ti": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "tig": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "tk": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "tl": {
    nplurals: 2,
    plural: "((n==1 || n==2 || n==3) || !(n%10==4 || n%10==6 || n%10==9)) ? 0 : 1",
    forms: ["one","other"],
  },
  "tn": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "to": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "tpi": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "tr": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ts": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "tzm": {
    nplurals: 2,
    plural: "((n>=0 && n<=1) || (n>=11 && n<=99)) ? 0 : 1",
    forms: ["one","other"],
  },
  "ug": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "uk": {
    nplurals: 3,
    plural: "((n%10==1 && !(n%100==11))) ? 0 : (((n%10>=2 && n%10<=4) && !(n%100>=12 && n%100<=14))) ? 1 : 2",
    forms: ["one","few","many"],
  },
  "und": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "ur": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "uz": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "ve": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "vec": {
    nplurals: 3,
    plural: "(n==1) ? 0 : ((!(n==0) && n%1000000==0)) ? 1 : 2",
    forms: ["one","many","other"],
  },
  "vi": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "vo": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "vun": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "wa": {
    nplurals: 2,
    plural: "((n>=0 && n<=1)) ? 0 : 1",
    forms: ["one","other"],
  },
  "wae": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "wo": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "xh": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "xog": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "yi": {
    nplurals: 2,
    plural: "(n==1) ? 0 : 1",
    forms: ["one","other"],
  },
  "yo": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "yue": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "zh": {
    nplurals: 1,
    plural: "0",
    forms: ["other"],
  },
  "zu": {
    nplurals: 2,
    plural: "(n==0 || n==1) ? 0 : 1",
    forms: ["one","other"],
  },
};
