// The write side of the built-in adapters (§3, §8): translations back
// into repo files, format-preserving so an unchanged catalog round-trips
// byte-identical. Pure: file contents in, file contents out.
//
// A messages file is edited in place (splice.ts): a changed value, a
// removed key or an added key touches only its own bytes, so a pull or
// a proposal reads as the lines it changes, whatever the file's layout.
// The base is the existing target file when there is one, else the
// source template. With an existing file, ids the translations do not
// mention keep their existing value; with only the template, they are
// omitted. New ids append in the given order, nested by dots when the
// file nests, flat when it is flat. TS-module sources are read-only
// here (see DECISIONS.md): only JSON files can be regenerated byte for
// byte.
import { addLeaf, checkPath, deleteLeaf, editLeaf } from "./splice";

type Tree = { [key: string]: string | Tree };
type Style = { indent: string; trailingNewline: boolean };

const DEFAULT_STYLE: Style = { indent: "  ", trailingNewline: true };

function styleOf(text: string): Style {
  if (text.trim() === "") return DEFAULT_STYLE;
  const indented = /^([ \t]+)\S/m.exec(text);
  return {
    indent: indented?.[1] ?? DEFAULT_STYLE.indent,
    trailingNewline: text.endsWith("\n"),
  };
}

function parseTree(text: string): Tree {
  if (text.trim() === "") return {};
  const parsed: unknown = JSON.parse(text);
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("messages: file must be a JSON object");
  }
  return parsed as Tree;
}

function leaves(
  tree: Tree,
  path: string[] = [],
  out: [string[], string][] = [],
): [string[], string][] {
  for (const [key, value] of Object.entries(tree)) {
    if (typeof value === "string") out.push([[...path, key], value]);
    else leaves(value, [...path, key], out);
  }
  return out;
}

function isNested(tree: Tree): boolean {
  return Object.values(tree).some((value) => typeof value !== "string");
}

function setPath(tree: Tree, path: string[], value: string): void {
  checkPath(path);
  let node = tree;
  for (const key of path.slice(0, -1)) {
    const next = node[key];
    if (typeof next === "string") {
      // A literal sits where nesting would go: a flat key at the root, as
      // the splice writes it, so the id reads back as itself.
      const flat = path.join(".");
      if (typeof tree[flat] === "object") collision(flat);
      tree[flat] = value;
      return;
    }
    node = next ?? (node[key] = {});
  }
  const last = path[path.length - 1]!;
  if (typeof node[last] === "object") collision(path.join("."));
  node[last] = value;
}

// An id equal to a nested key path cannot live in this file's shape;
// failing loudly beats overwriting the subtree.
function collision(id: string): never {
  throw new Error(
    `messages: id ${JSON.stringify(id)} collides with a nested key path`,
  );
}

// `locale` is an .arb's language. A missing .json is the template with
// the strings swapped and the rest deleted, which for an .arb would leave
// the source's `@@locale` and the shells of its `@key` metadata behind;
// a missing .arb is written from the template's strings alone, with
// `@@locale` first, since gen-l10n reads the locale from it before the
// file name (#568). The `@key` metadata stays in the source, where
// gen-l10n reads it.
export function entriesToMessages(
  template: string,
  translations: Record<string, string>,
  existing?: string,
  options: { locale?: string } = {},
): string {
  const base = existing !== undefined ? existing : template;
  const missing = existing === undefined || existing.trim() === "";
  if (base.trim() === "" || (missing && options.locale !== undefined))
    return fromTemplate(template, translations, options.locale);
  const baseTree = parseTree(base);
  const style = styleOf(base);
  const nested = isNested(baseTree);
  let text = base;
  const seen = new Set<string>();
  for (const [path, value] of leaves(baseTree)) {
    const id = path.join(".");
    seen.add(id);
    const next = translations[id];
    if (next !== undefined) {
      if (next !== value) text = editLeaf(text, path, next) ?? text;
    } else if (existing === undefined) {
      text = deleteLeaf(text, path);
    }
  }
  for (const id of Object.keys(translations)) {
    if (seen.has(id)) continue;
    text = addLeaf(
      text,
      nested ? id.split(".") : [id],
      translations[id]!,
      style.indent,
    );
  }
  return text;
}

// An empty file has no bytes to keep: the template's structure and
// style, rewritten, as the first pull into a new target file.
function fromTemplate(
  template: string,
  translations: Record<string, string>,
  locale?: string,
): string {
  const style = styleOf(template);
  const tree = parseTree(template);
  const nested = isNested(tree);
  const out: Tree = Object.create(null) as Tree;
  if (locale !== undefined) out["@@locale"] = locale;
  const seen = new Set<string>();
  for (const [path] of leaves(tree)) {
    const id = path.join(".");
    seen.add(id);
    const value = translations[id];
    if (value !== undefined) setPath(out, path, value);
  }
  for (const id of Object.keys(translations)) {
    if (seen.has(id)) continue;
    setPath(out, nested ? id.split(".") : [id], translations[id]!);
  }
  return (
    JSON.stringify(out, null, style.indent) +
    (style.trailingNewline ? "\n" : "")
  );
}

type Record_ = Record<string, unknown>;

function parseRecords(text: string): Record_[] {
  if (text.trim() === "") return [];
  const parsed: unknown = JSON.parse(text);
  if (!Array.isArray(parsed))
    throw new Error("table: file must be a JSON array");
  return parsed as Record_[];
}

// Two record layouts are recognised: one record per line, or fully
// expanded (JSON.stringify's). Anything else is rewritten as expanded.
function oneRecordPerLine(text: string, count: number): boolean {
  const lines = text.trim().split("\n");
  return count > 0 && lines.length === count + 2;
}

function inlineRecord(record: Record_): string {
  const fields = Object.entries(record).map(
    ([key, value]) => `${JSON.stringify(key)}: ${JSON.stringify(value)}`,
  );
  return fields.length ? `{ ${fields.join(", ")} }` : "{}";
}

export function entriesToTable(
  template: string,
  translations: Record<string, string>,
  map: { id: string; text: string },
  existing?: string,
): string {
  const base = existing !== undefined ? existing : template;
  const style = styleOf(base);
  const baseRecords = parseRecords(base);
  const inline = oneRecordPerLine(base, baseRecords.length);

  const out: Record_[] = [];
  const seen = new Set<string>();
  const emit = (record: Record_, fallback: boolean) => {
    const id = String(record[map.id]);
    seen.add(id);
    const text = translations[id];
    if (text === undefined && !fallback) return;
    out.push({ ...record, [map.text]: text ?? record[map.text] });
  };
  for (const record of baseRecords) emit(record, existing !== undefined);
  if (existing !== undefined) {
    for (const record of parseRecords(template)) {
      if (!seen.has(String(record[map.id]))) emit(record, false);
    }
  }

  const body = inline
    ? `[\n${out.map((r) => style.indent + inlineRecord(r)).join(",\n")}\n]`
    : JSON.stringify(out, null, style.indent);
  return body + (style.trailingNewline ? "\n" : "");
}

// Source-side operations (§8, §11): a proposal sets, adds or removes a
// key in the source-language file, and a removal leaves the target
// files too, each touching only its own bytes. An edit of an absent id
// adds it; a delete of an absent id is nothing.
export type SourceOp =
  | { kind: "edit" | "add"; id: string; text: string }
  | { kind: "delete"; id: string };

export function applyMessagesOps(text: string, ops: SourceOp[]): string {
  if (text.trim() === "") text = "{}\n";
  const nested = isNested(parseTree(text));
  const { indent } = styleOf(text);
  let out = text;
  for (const op of ops) {
    const path = nested ? op.id.split(".") : [op.id];
    if (op.kind === "delete") {
      // Absent already (a second pull, a target file without the key):
      // nothing to do; the push that lands the removal marks it applied.
      const next = deleteLeaf(out, path);
      out = next === out ? deleteLeaf(out, [op.id]) : next;
    } else {
      out = editLeaf(out, path, op.text) ?? addLeaf(out, path, op.text, indent);
    }
  }
  return out;
}

export function applyTableOps(
  text: string,
  ops: SourceOp[],
  map: { id: string; text: string },
): string {
  const records = parseRecords(text);
  const style = styleOf(text);
  const inline = oneRecordPerLine(text, records.length);
  let out = records.map((record) => ({ ...record }));
  for (const op of ops) {
    const index = out.findIndex((r) => String(r[map.id]) === op.id);
    if (op.kind === "delete") {
      if (index >= 0) out = out.filter((_, i) => i !== index);
    } else if (index >= 0) {
      out[index] = { ...out[index]!, [map.text]: op.text };
    } else {
      out.push({ [map.id]: op.id, [map.text]: op.text });
    }
  }
  const body = inline
    ? `[\n${out.map((r) => style.indent + inlineRecord(r)).join(",\n")}\n]`
    : JSON.stringify(out, null, style.indent);
  return body + (style.trailingNewline ? "\n" : "");
}
