// The write side of the built-in adapters (§3, §8): translations back
// into repo files, format-preserving so an unchanged catalog round-trips
// byte-identical. Pure: file contents in, file contents out.
//
// A messages file is edited in place (splice.ts): a changed value, a
// removed key or an added key touches only its own bytes, so a pull or
// a proposal reads as the lines it changes, whatever the file's layout.
// The base is the existing target file when there is one, else the
// source template. With an existing file, ids the translations do not
// mention keep their existing value; with only the template, they are
// omitted. A new id goes beside its neighbours in the source file
// (#654), at the key path the source file gives it (split on dots only
// when it holds none, nested when the file nests, flat when it is flat).
// TS-module sources are read-only here (see DECISIONS.md): only JSON
// files can be regenerated byte for byte.
import { PLURAL_CATEGORIES } from "@corpus/contract";
import {
  isPluralAt,
  pluralBranches,
  pluralText,
  type PluralObjects,
} from "./messages";
import {
  addLeaf,
  checkPath,
  deleteKey,
  deleteLeaf,
  editLeaf,
  keyOrder,
} from "./splice";
import { eolOf, ownRecord } from "./text";

type Tree = { [key: string]: string | Tree };
type Style = { indent: string; trailingNewline: boolean };

const DEFAULT_STYLE: Style = { indent: "  ", trailingNewline: true };

function styleOf(text: string): Style {
  if (text.trim() === "") return DEFAULT_STYLE;
  const indented = /^([ \t]+)\S/m.exec(text);
  return {
    indent: indented?.[1] ?? DEFAULT_STYLE.indent,
    trailingNewline: text.endsWith("\n"),
  };
}

function parseTree(text: string): Tree {
  if (text.trim() === "") return {};
  const parsed: unknown = JSON.parse(stripBom(text));
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("messages: file must be a JSON object");
  }
  return parsed as Tree;
}

// A BOM is kept in the text, which the splice edits around; only
// JSON.parse refuses it.
export function stripBom(text: string): string {
  return text.startsWith("\uFEFF") ? text.slice(1) : text;
}

type Leaf = [path: string[], value: string, plural: boolean];

// With `plurals`, a plural object is one leaf, its text the plural
// string it reads as (#662); at an id of `known`, the source's plurals,
// one without `other` too (#950).
function leaves(
  tree: Tree,
  plurals: PluralObjects = false,
  known?: ReadonlySet<string>,
  path: string[] = [],
  out: Leaf[] = [],
): Leaf[] {
  for (const [key, value] of Object.entries(tree)) {
    const at = [...path, key];
    if (typeof value === "string") out.push([at, value, false]);
    else if (isPluralAt(value, at.join("."), plurals, known))
      out.push([at, pluralText("count", value, "written"), true]);
    else leaves(value, plurals, known, at, out);
  }
  return out;
}

// Each id's key path as a file writes it, and the ids that are plural
// objects: a segment may hold dots (`"m.room.topic": { … }`), so an id
// is never split to find its place when a file already names it (#642).
function keyPaths(
  tree: Tree,
  plurals: PluralObjects = false,
): { paths: Map<string, string[]>; pluralIds: Set<string> } {
  const found = leaves(tree, plurals);
  return {
    paths: new Map(found.map(([path]) => [path.join("."), path])),
    pluralIds: new Set(
      found.filter(([, , plural]) => plural).map(([path]) => path.join(".")),
    ),
  };
}

// Why an id's text was not written, for the caller to say.
export type Refusal = (id: string, text: string) => void;

// The forms a translation of a plural object writes: its branches, or a
// plain text as the other form; undefined for a plural the object cannot
// hold, an `=0` branch or a brace a form leaves open, which would
// otherwise land whole in `other`.
function formsOf(text: string): Record<string, string> | undefined {
  const forms = pluralBranches(text);
  if (forms) return forms;
  return /^\s*\{\s*[\p{L}_][\p{L}\p{M}\p{N}_.-]*\s*,\s*plural\s*,/u.test(text)
    ? undefined
    : { other: text };
}

// A plural written as the object its file keeps (#662): each form of
// the text at `path.form`, in CLDR's order, and a form the text no
// longer has removed; a text that is not a plural is the `other` form.
function writePlural(
  text: string,
  path: string[],
  plural: string,
  unit: string,
  order?: (objectPath: string[]) => string[] | undefined,
  onRefused?: Refusal,
): string {
  const forms = formsOf(plural);
  if (!forms) {
    onRefused?.(path.join("."), plural);
    return text;
  }
  const at = path.join("\u0000");
  const inOrder = (objectPath: string[]) =>
    objectPath.join("\u0000") === at
      ? [...PLURAL_CATEGORIES]
      : order?.(objectPath);
  let current: unknown = parseTree(text);
  for (const key of path)
    current =
      current && typeof current === "object"
        ? (current as Tree)[key]
        : undefined;
  let out = text;
  if (typeof current === "string") {
    out = deleteKey(out, path);
    current = undefined;
  }
  for (const form of PLURAL_CATEGORIES) {
    const value = forms[form];
    if (value === undefined) continue;
    const leaf = [...path, form];
    out =
      editLeaf(out, leaf, value) ?? addLeaf(out, leaf, value, unit, inOrder);
  }
  if (current && typeof current === "object")
    for (const form of Object.keys(current))
      if (!Object.hasOwn(forms, form)) out = deleteLeaf(out, [...path, form]);
  return out;
}

function isNested(tree: Tree): boolean {
  return Object.values(tree).some((value) => typeof value !== "string");
}

function setPath(tree: Tree, path: string[], value: string): void {
  checkPath(path);
  const own = (at: Tree, key: string) =>
    Object.hasOwn(at, key) ? at[key] : undefined;
  let node = tree;
  for (const key of path.slice(0, -1)) {
    const next = own(node, key);
    if (typeof next === "string") {
      // A literal sits where nesting would go: a flat key at the root, as
      // the splice writes it, so the id reads back as itself.
      const flat = path.join(".");
      if (typeof own(tree, flat) === "object") collision(flat);
      tree[flat] = value;
      return;
    }
    node = next ?? (node[key] = Object.create(null) as Tree);
  }
  const last = path[path.length - 1]!;
  if (typeof own(node, last) === "object") collision(path.join("."));
  node[last] = value;
}

// An id equal to a nested key path cannot live in this file's shape;
// failing loudly beats overwriting the subtree.
function collision(id: string): never {
  throw new Error(
    `messages: id ${JSON.stringify(id)} collides with a nested key path`,
  );
}

// `locale` is an .arb's language. A missing .json is the template with
// the strings swapped and the rest deleted, which for an .arb would leave
// the source's `@@locale` and the shells of its `@key` metadata behind;
// a missing .arb is written from the template's strings alone, with
// `@@locale` first, since gen-l10n reads the locale from it before the
// file name (#568), in the underscore form: gen-l10n compares `@@locale`
// as written with the file name's locale normalised to underscores and
// refuses a mismatch, so `pt-PT` is written `pt_PT` whatever the file
// name says (#585). The `@key` metadata stays in the source, where
// gen-l10n reads it.
export function entriesToMessages(
  template: string,
  translations: Record<string, string>,
  existing?: string,
  options: {
    locale?: string;
    chrome?: boolean;
    plurals?: PluralObjects;
    onRefused?: Refusal;
  } = {},
): string {
  translations = ownRecord(translations);
  if (options.chrome) return chromeMessages(template, translations, existing);
  const plurals = options.plurals ?? false;
  const onRefused = options.onRefused;
  const base = existing !== undefined ? existing : template;
  const missing = existing === undefined || existing.trim() === "";
  if (base.trim() === "" || (missing && options.locale !== undefined))
    return fromTemplate(
      template,
      translations,
      options.locale,
      plurals,
      onRefused,
    );
  const baseTree = parseTree(base);
  const style = styleOf(base);
  const nested = isNested(baseTree);
  const sourceTree = parseTree(template);
  const { paths: sourcePaths, pluralIds: sourcePlurals } = keyPaths(
    sourceTree,
    plurals,
  );
  const order = keyOrder(stripBom(template));
  let text = base;
  const seen = new Set<string>();
  for (const [path, value, plural] of leaves(
    baseTree,
    plurals,
    sourcePlurals,
  )) {
    const id = path.join(".");
    seen.add(id);
    const next = translations[id];
    if (next !== undefined) {
      if (next === value) continue;
      text =
        plural || sourcePlurals.has(id)
          ? writePlural(text, path, next, style.indent, order, onRefused)
          : (editLeaf(text, path, next) ?? text);
    } else if (existing === undefined) {
      text = plural ? deleteKey(text, path) : deleteLeaf(text, path);
    }
  }
  for (const id of Object.keys(translations)) {
    if (seen.has(id)) continue;
    const path = sourcePaths.get(id) ?? (nested ? id.split(".") : [id]);
    text = sourcePlurals.has(id)
      ? writePlural(
          text,
          path,
          translations[id]!,
          style.indent,
          order,
          onRefused,
        )
      : addLeaf(text, path, translations[id]!, style.indent, order);
  }
  return text;
}

// Chrome i18n (#595): a translation is an entry's `message`, edited in
// place; the rest of the entry is the source's, copied with a new key.
// A missing or blank file starts from the source, BOM and all.
function chromeMessages(
  template: string,
  translations: Record<string, string>,
  existing: string | undefined,
): string {
  const fresh = existing === undefined || existing.trim() === "";
  let text = fresh ? template : existing;
  const source = parseTree(template);
  const base = parseTree(text);
  const { indent } = styleOf(text);
  for (const [id, entry] of Object.entries(base)) {
    const next = Object.hasOwn(translations, id) ? translations[id] : undefined;
    if (next === undefined) {
      if (fresh) text = deleteKey(text, [id]);
    } else if (typeof entry !== "object" || entry.message !== next) {
      text =
        editLeaf(text, [id, "message"], next) ??
        addLeaf(text, [id, "message"], next, indent);
    }
  }
  for (const [id, next] of Object.entries(translations)) {
    if (Object.hasOwn(base, id)) continue;
    const model = source[id];
    const fields: [string[], string][] =
      typeof model === "object"
        ? leaves(model).map(([path, value]) => [path, value])
        : [[["message"], next]];
    for (const [path, value] of fields) {
      const field = path.join(".") === "message" ? next : value;
      text = addLeaf(text, [id, ...path], field, indent);
    }
  }
  return text;
}

// An empty file has no bytes to keep: the template's structure and
// style, rewritten, as the first pull into a new target file.
function fromTemplate(
  template: string,
  translations: Record<string, string>,
  locale?: string,
  plurals: PluralObjects = false,
  onRefused?: Refusal,
): string {
  const style = styleOf(template);
  const tree = parseTree(template);
  const nested = isNested(tree);
  const out: Tree = Object.create(null) as Tree;
  if (locale !== undefined) out["@@locale"] = locale.replaceAll("-", "_");
  const seen = new Set<string>();
  for (const [path, , plural] of leaves(tree, plurals)) {
    const id = path.join(".");
    seen.add(id);
    const value = translations[id];
    if (value === undefined) continue;
    if (!plural) setPath(out, path, value);
    else {
      const forms = formsOf(value);
      if (!forms) {
        onRefused?.(id, value);
        continue;
      }
      for (const form of PLURAL_CATEGORIES)
        if (forms[form] !== undefined)
          setPath(out, [...path, form], forms[form]);
    }
  }
  for (const id of Object.keys(translations)) {
    if (seen.has(id)) continue;
    setPath(out, nested ? id.split(".") : [id], translations[id]!);
  }
  // The template's line endings and BOM (#850).
  return likeFile(
    JSON.stringify(out, null, style.indent) +
      (style.trailingNewline ? "\n" : ""),
    template,
  );
}

// JSON written as `like` is: its line endings and its BOM. JSON escapes
// a line break inside a string, so every one here is the layout's.
function likeFile(json: string, like: string): string {
  const bom = like.startsWith("\uFEFF") ? "\uFEFF" : "";
  return bom + json.replace(/\n/g, eolOf(like));
}

type Record_ = Record<string, unknown>;

function parseRecords(text: string): Record_[] {
  if (text.trim() === "") return [];
  const parsed: unknown = JSON.parse(stripBom(text));
  if (!Array.isArray(parsed))
    throw new Error("table: file must be a JSON array");
  return parsed as Record_[];
}

// Two record layouts are recognised: one record per line, or fully
// expanded (JSON.stringify's). Anything else is rewritten as expanded.
function oneRecordPerLine(text: string, count: number): boolean {
  const lines = text.trim().split("\n");
  return count > 0 && lines.length === count + 2;
}

function inlineRecord(record: Record_): string {
  const fields = Object.entries(record).map(
    ([key, value]) => `${JSON.stringify(key)}: ${JSON.stringify(value)}`,
  );
  return fields.length ? `{ ${fields.join(", ")} }` : "{}";
}

export function entriesToTable(
  template: string,
  translations: Record<string, string>,
  map: { id: string; text: string },
  existing?: string,
): string {
  translations = ownRecord(translations);
  // A blank file is a new one: the template's layout, line endings and
  // BOM (#883).
  if (existing?.trim() === "") existing = undefined;
  // One with no records keeps its own BOM and line endings but takes the
  // template's layout, which `[]` cannot show, and is left as it is when
  // nothing goes into it (#927).
  const empty = existing !== undefined && parseRecords(existing).length === 0;
  const fresh = existing === undefined || empty;
  const base = fresh ? template : existing!;
  const style = styleOf(base);
  const baseRecords = parseRecords(base);
  const inline = oneRecordPerLine(base, baseRecords.length);

  const out: Record_[] = [];
  const seen = new Set<string>();
  const emit = (record: Record_, fallback: boolean) => {
    const id = String(record[map.id]);
    seen.add(id);
    const text = translations[id];
    if (text === undefined && !fallback) return;
    out.push({ ...record, [map.text]: text ?? record[map.text] });
  };
  for (const record of baseRecords) emit(record, !fresh);
  if (!fresh) {
    for (const record of parseRecords(template)) {
      if (!seen.has(String(record[map.id]))) emit(record, false);
    }
  }

  if (!empty) return renderRecords(out, style, inline, base);
  if (out.length === 0) return existing!;
  const own = existing!.startsWith("\uFEFF") ? "\uFEFF" : "";
  return renderRecords(
    out,
    style,
    inline,
    own + eolOf(existing!.includes("\n") ? existing! : template),
  );
}

// A table's records in the file's layout: one record a line where the
// file writes them so, else JSON's own, written as `like` is (#883).
function renderRecords(
  records: Record_[],
  style: Style,
  inline: boolean,
  like: string,
): string {
  // No records is `[]`, whose layout no pull could tell again.
  const body =
    inline && records.length > 0
      ? `[\n${records.map((r) => style.indent + inlineRecord(r)).join(",\n")}\n]`
      : JSON.stringify(records, null, style.indent);
  return likeFile(body + (style.trailingNewline ? "\n" : ""), like);
}

// Source-side operations (§8, §11): a proposal sets, adds or removes a
// key in the source-language file, and a removal leaves the target
// files too, each touching only its own bytes. An edit of an absent id
// adds it; a delete of an absent id is nothing.
export type SourceOp =
  | { kind: "edit" | "add"; id: string; text: string }
  | { kind: "delete"; id: string };

export function applyMessagesOps(
  text: string,
  ops: SourceOp[],
  options: { chrome?: boolean; plurals?: PluralObjects } = {},
): string {
  if (text.trim() === "") text = "{}\n";
  if (options.chrome) return chromeOps(text, ops);
  const tree = parseTree(text);
  const nested = isNested(tree);
  const plurals = options.plurals ?? false;
  const { paths, pluralIds } = keyPaths(tree, plurals);
  const { indent } = styleOf(text);
  let out = text;
  for (const op of ops) {
    const path = paths.get(op.id) ?? (nested ? op.id.split(".") : [op.id]);
    if (op.kind === "delete") {
      // Absent already (a second pull, a target file without the key):
      // nothing to do; the push that lands the removal marks it applied.
      const next = pluralIds.has(op.id)
        ? deleteKey(out, path)
        : deleteLeaf(out, path);
      out = next === out ? deleteLeaf(out, [op.id]) : next;
    } else if (pluralIds.has(op.id)) {
      // A proposal the object cannot hold fails the file loudly: it is
      // counted written otherwise, and never lands.
      out = writePlural(out, path, op.text, indent, undefined, (id) => {
        throw new Error(
          `messages: ${id} is a plural its object cannot hold (an =N branch, or a brace a form leaves open)`,
        );
      });
    } else {
      out = editLeaf(out, path, op.text) ?? addLeaf(out, path, op.text, indent);
    }
  }
  return out;
}

function chromeOps(text: string, ops: SourceOp[]): string {
  const { indent } = styleOf(text);
  let out = text;
  for (const op of ops) {
    out =
      op.kind === "delete"
        ? deleteKey(out, [op.id])
        : (editLeaf(out, [op.id, "message"], op.text) ??
          addLeaf(out, [op.id, "message"], op.text, indent));
  }
  return out;
}

export function applyTableOps(
  text: string,
  ops: SourceOp[],
  map: { id: string; text: string },
): string {
  const records = parseRecords(text);
  const style = styleOf(text);
  const inline = oneRecordPerLine(text, records.length);
  let out = records.map((record) => ({ ...record }));
  for (const op of ops) {
    const index = out.findIndex((r) => String(r[map.id]) === op.id);
    if (op.kind === "delete") {
      if (index >= 0) out = out.filter((_, i) => i !== index);
    } else if (index >= 0) {
      out[index] = { ...out[index]!, [map.text]: op.text };
    } else {
      out.push({ [map.id]: op.id, [map.text]: op.text });
    }
  }
  return renderRecords(out, style, inline, text);
}
