// The write side of the built-in adapters (§3, §8): translations back
// into repo files, format-preserving so an unchanged catalog round-trips
// byte-identical. Pure: file contents in, file contents out.
//
// Structure, key order, indentation and trailing newline come from the
// existing target file when there is one, else from the source template.
// With an existing file, ids the translations do not mention keep their
// existing value; with only the template, they are omitted. New ids
// append in the given order, nested by dots when the file nests, flat
// when it is flat. TS-module sources are read-only here (see
// DECISIONS.md): only JSON files can be regenerated byte for byte.

type Tree = { [key: string]: string | Tree };
type Style = { indent: string; trailingNewline: boolean };

const DEFAULT_STYLE: Style = { indent: "  ", trailingNewline: true };

function styleOf(text: string): Style {
  if (text.trim() === "") return DEFAULT_STYLE;
  const indented = /^([ \t]+)\S/m.exec(text);
  return {
    indent: indented?.[1] ?? DEFAULT_STYLE.indent,
    trailingNewline: text.endsWith("\n"),
  };
}

function parseTree(text: string): Tree {
  if (text.trim() === "") return {};
  const parsed: unknown = JSON.parse(text);
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("messages: file must be a JSON object");
  }
  return parsed as Tree;
}

function leaves(
  tree: Tree,
  path: string[] = [],
  out: [string[], string][] = [],
): [string[], string][] {
  for (const [key, value] of Object.entries(tree)) {
    if (typeof value === "string") out.push([[...path, key], value]);
    else leaves(value, [...path, key], out);
  }
  return out;
}

function isNested(tree: Tree): boolean {
  return Object.values(tree).some((value) => typeof value !== "string");
}

const UNSAFE_SEGMENTS = new Set(["__proto__", "constructor", "prototype"]);

function setPath(tree: Tree, path: string[], value: string): void {
  // An id from the server is data; these segments would walk into the
  // prototype instead of the tree.
  if (path.some((segment) => UNSAFE_SEGMENTS.has(segment))) {
    throw new Error(
      `messages: id ${JSON.stringify(path.join("."))} is not a valid key path`,
    );
  }
  let node = tree;
  for (const key of path.slice(0, -1)) {
    const next = node[key];
    if (typeof next === "string") {
      // A literal sits where nesting would go: fall back to a flat key.
      node[path.join(".")] = value;
      return;
    }
    node = next ?? (node[key] = {});
  }
  const last = path[path.length - 1]!;
  if (typeof node[last] === "object") {
    // An id equal to a nested key path cannot live in this file's shape;
    // failing loudly beats overwriting the subtree.
    throw new Error(
      `messages: id ${JSON.stringify(path.join("."))} collides with a nested key path`,
    );
  }
  node[last] = value;
}

export function entriesToMessages(
  template: string,
  translations: Record<string, string>,
  existing?: string,
): string {
  const base = existing !== undefined ? existing : template;
  const baseTree = parseTree(base);
  const style = styleOf(base.trim() === "" ? template : base);
  const nested =
    isNested(baseTree) ||
    (existing !== undefined &&
      !existing.trim() &&
      isNested(parseTree(template)));

  // Null-prototype, so a flat key such as __proto__ is an own key.
  const out: Tree = Object.create(null) as Tree;
  const seen = new Set<string>();
  const place = (path: string[], fallback: string | undefined) => {
    const id = path.join(".");
    seen.add(id);
    const value = translations[id] ?? fallback;
    if (value !== undefined) setPath(out, path, value);
  };
  for (const [path, value] of leaves(baseTree)) {
    place(path, existing !== undefined ? value : undefined);
  }
  if (existing !== undefined) {
    for (const [path] of leaves(parseTree(template))) {
      if (!seen.has(path.join("."))) place(path, undefined);
    }
  }
  for (const id of Object.keys(translations)) {
    if (seen.has(id)) continue;
    setPath(out, nested ? id.split(".") : [id], translations[id]!);
  }

  return (
    JSON.stringify(out, null, style.indent) +
    (style.trailingNewline ? "\n" : "")
  );
}

type Record_ = Record<string, unknown>;

function parseRecords(text: string): Record_[] {
  if (text.trim() === "") return [];
  const parsed: unknown = JSON.parse(text);
  if (!Array.isArray(parsed))
    throw new Error("table: file must be a JSON array");
  return parsed as Record_[];
}

// Two record layouts are recognised: one record per line, or fully
// expanded (JSON.stringify's). Anything else is rewritten as expanded.
function oneRecordPerLine(text: string, count: number): boolean {
  const lines = text.trim().split("\n");
  return count > 0 && lines.length === count + 2;
}

function inlineRecord(record: Record_): string {
  const fields = Object.entries(record).map(
    ([key, value]) => `${JSON.stringify(key)}: ${JSON.stringify(value)}`,
  );
  return fields.length ? `{ ${fields.join(", ")} }` : "{}";
}

export function entriesToTable(
  template: string,
  translations: Record<string, string>,
  map: { id: string; text: string },
  existing?: string,
): string {
  const base = existing !== undefined ? existing : template;
  const style = styleOf(base);
  const baseRecords = parseRecords(base);
  const inline = oneRecordPerLine(base, baseRecords.length);

  const out: Record_[] = [];
  const seen = new Set<string>();
  const emit = (record: Record_, fallback: boolean) => {
    const id = String(record[map.id]);
    seen.add(id);
    const text = translations[id];
    if (text === undefined && !fallback) return;
    out.push({ ...record, [map.text]: text ?? record[map.text] });
  };
  for (const record of baseRecords) emit(record, existing !== undefined);
  if (existing !== undefined) {
    for (const record of parseRecords(template)) {
      if (!seen.has(String(record[map.id]))) emit(record, false);
    }
  }

  const body = inline
    ? `[\n${out.map((r) => style.indent + inlineRecord(r)).join(",\n")}\n]`
    : JSON.stringify(out, null, style.indent);
  return body + (style.trailingNewline ? "\n" : "");
}
